name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # Trigger workflow on push to 'main' branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - api-node
          - api-golang
          - client-react

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Changed Files
        id: changes
        run: |
          echo "Checking for changes in ${{ matrix.service }}..."
          if git diff --name-only ${{ github.sha }} ${{ github.sha }}^ | grep "^${{ matrix.service }}/"; then
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "changes_detected=false" >> $GITHUB_ENV
          fi

      - name: Build and Push ${{ matrix.service }} Image
        if: env.changes_detected == 'true'
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}               # Navigate to each service directory
          file: ./${{ matrix.service }}/Dockerfile       # Use the Dockerfile in each folder
          push: true                                     # Push the image to Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service }}:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}      # Securely pass the database URL
